### ISSUE TITLE
Initialize project.

### ISSUE THREAD

**Issue by proofit404** [proofit404/typedsql#2]
```toml
[tool.poetry]
name = "typedsql"
version = "0.0.1.dev0"
description = "Typing-friendly raw SQL query executor."
authors = ["Josiah Kaviani <proofit404@gmail.com>"]
license = "BSD-2-Clause"
readme = "README.md"

[tool.poetry.dependencies]
python = "*"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
```
